Nieuwe versie van inonderzoek voor adressen (uitgebreid) toegevoegd o…
lvbag/BAG-API pull request #25
Opened 2020-11-25 16:27 UTC by strijm

…ude verwijderd

2020-11-26 16:52 UTC, kad-voordm requested changes

2020-11-26 16:52 UTC, kad-voordm commented on Features/inonderzoek-bij-adressen-en-adressen-uitgebreid.feature
> +    En het <Attibuut in de BAG> dat in onderzoek is, is relevant voor een Adres of voor Adres uitgebreid
.. <Attribuut ...

2020-11-26 16:52 UTC, kad-voordm commented on Features/inonderzoek-bij-adressen-en-adressen-uitgebreid.feature
> +    Als de /adressen of /adressenuitgebreid wordt bevraagd
'de' weg?

2020-11-26 17:19 UTC, strijm commented on Features/inonderzoek-bij-adressen-en-adressen-uitgebreid.feature
> +    En het <Attibuut in de BAG> dat in onderzoek is, is relevant voor een Adres of voor Adres uitgebreid
Aangepast

2020-11-26 17:19 UTC, strijm commented on Features/inonderzoek-bij-adressen-en-adressen-uitgebreid.feature
> +    Als de /adressen of /adressenuitgebreid wordt bevraagd
Aangepast

2020-11-26 17:25 UTC, kad-voordm approved these changes

2020-11-27 07:34 UTC, kad-kleijm approved these changes

2020-11-27 07:38 UTC, merged