Initiële versie tijdreizen.feature
lvbag/BAG-API pull request #62
Opened 2022-10-11 13:35 UTC by strijm

Graag reviewen en controleren op correctheid, compleetheid, consistentie met andere feature beschrijvingen, opmaak, taal-/spelfouten.

2022-10-27 11:44 UTC, kad-kleijm commented on Features/tijdreizen.feature
> +  - bronhouder
Moet de resource `adresseerbareobjecten` nog aan dit lijstje worden toegevoegd?

2022-10-27 11:48 UTC, kad-kleijm commented on Features/tijdreizen.feature
> +  ss	  Seconden 2 cijfers (00 to 59)
Willen we het Engelse `to` of het Nederlandse `tot`? En zou het dan technisch gezien `tot en met` moeten zijn?

2022-10-27 13:08 UTC, kad-kleijm commented on Features/tijdreizen.feature
> +    En de status van het betreffende object voorkomen is geen eindstatus
`geen` moet `een` zijn?

2022-10-27 15:09 UTC, lvbag commented on Features/tijdreizen.feature
> +    | Niet toegestane parametercombinatie | 400    | De combinatie van opgegeven parameters is niet toegestaan. | unsupportedCombi  |
Ik heb hier met Mark over gesproken. Ik ben van mening dat het netter is om de afnemer een foutmelding terug te geven, zodat het duidelijk is dat er iets mis is met de bevraging en er niets wordt gedaan met de parameters. Er is nog niet besproken hoe en waar dit wordt beschreven en of dit breaking is voor afnemers op dit moment.

2022-10-27 20:26 UTC, kad-kleijm commented on Features/tijdreizen.feature
> +    | Niet toegestane parametercombinatie | 400    | De combinatie van opgegeven parameters is niet toegestaan. | unsupportedCombi  |
Bij de bag-api hanteren we de code `unsupportedCombination`, zie ook https://github.com/lvbag/BAG-API/blob/master/Features/foutafhandeling.feature#L17

2022-10-31 14:52 UTC, strijm commented on Features/tijdreizen.feature
> +    | Niet toegestane parametercombinatie | 400    | De combinatie van opgegeven parameters is niet toegestaan. | unsupportedCombi  |
We hebben besloten om in de huidige major versie geen foutmelding te geven, maar dit in een volgende major versie  te implementeren. De redenen hiervoor:

- Voorkomen dat het gedrag van de BAG Individuele Bevragingen API endpoints anders wordt dan de huidige implementatie. Dit zou problemen kunnen veroorzaken in de huidige implementatie van afnemers.
- Voorkomen dat het gedrag van de BAG Individuele Bevragingen API endpoints onderling inconsistent wordt.
- Het is voor afnemers duidelijker als er een foutmelding optreedt wanneer er een request wordt ingediend die niet conform de API specificatie is. Als er geen fout optreedt maar een leeg resultaat wordt geretourneerd, is het voor een afnemer wellicht niet meteen duidelijk wat er verkeerd is (de request voldoet niet aan de API specificatie).

Het geven van deze foutmelding zal daarom op de backlog worden gezet en de beschrijving in de feature file wordt aangepast.

2022-10-31 16:25 UTC, kad-kleijm approved these changes

2022-11-01 07:40 UTC, kad-kleijm commented on Features/tijdreizen.feature
> +    En in de request wordt huidig=true opgegeven
Hier is nu specifiek `huidig=true` opgenomen. Klopt de volgende aanname dan?
"Als huidig=false is opgegeven en geldigOp en/of beschikbaarOp wordt opgegeven, dan krijg je geen validatiemelding."

Wat gebeurt er als je `huidig=true` opgeeft en `geldigOp=vandaag`?

2022-11-04 07:30 UTC, kad-kleijm requested changes

2022-11-04 07:30 UTC, kad-kleijm commented on Features/tijdreizen.feature
> +    Gegeven een endpoint die de parameters geldigOp, beschikbaarOp en huidig ondersteund
Taaltechnisch: `ondersteund` > `ondersteunt`

2022-11-04 07:30 UTC, kad-kleijm commented on Features/tijdreizen.feature
> +    Gegeven een endpoint die de parameters geldigOp, beschikbaarOp en huidig parameter ondersteund
Taaltechnisch: `ondersteund` > `ondersteunt`

2022-11-04 07:30 UTC, kad-kleijm commented on Features/tijdreizen.feature
> +    | null (nu)       | not null (< nu) | false  | geen eind status } tijdreisvraag naar wat er nu geldig is met kennis in het verleden ongeacht status en actuele voorkomen zonder eind status is nit
Taaltechnisch: `nit` > `niet`

2022-11-04 11:12 UTC, kad-kleijm commented on Features/tijdreizen.feature
> +    | not null (< nu) | not null (< nu) | true   | eind status      | tijdreisvraag naar wat er in het verleden geldig was met kennis in het verleden en actuele voorkomen zonder eind status is niet m
Wat doen we met geldigOp en beschikbaarOp waardes `> nu`?

2022-11-10 21:08 UTC, merged