Nathalie vos patch 1
lvbag/BAG-API pull request #70
Opened 2022-12-01 09:00 UTC by lvbag

Zou je naar het Getting Started document willen kijken voordat ik deze beschikbaar stel?

2022-12-01 15:25 UTC, strijm requested changes

2022-12-01 15:25 UTC, strijm commented on Getting started.md
> +In de tabel [Wat zit in welk endpoint](https://github.com/lvbag/BAG-API/blob/master/Documentatie/Tabel_Wat%20zit%20in%20welk%20endpoint_.pdf) is af te lezen welke zoekingangen mogelijk zijn bij de ve
De tabel in de PDF moet nog worden uitgebreid met de HC features.

2022-12-01 15:25 UTC, strijm commented on Getting started.md
> +
Er missen nog een aantal features en het zou goed zijn voor iedere feature een link naar het feature bestand op te nemen.

2022-12-02 10:14 UTC, kad-kleijm requested changes

2022-12-02 10:14 UTC, kad-kleijm commented on README.md
> +* Technische specificaties van de API in [Swagger-formaat](./Technische%20specificatie) of in [Redoc-formaat](./Technische%20specificatie)
Ik zou hier van maken:
`Technische specificaties van de API in [Swagger-formaat](https://lvbag.github.io/BAG-API/Technische%20specificatie/) of in [Redoc-formaat](https://lvbag.github.io/BAG-API/Technische%20specificatie/Redoc/)`

2023-02-07 14:44 UTC, strijm commented on Getting started.md
> +
Link opgenomen naar map met features.

2023-02-07 14:44 UTC, merged